[package]
name = "shterm-redirect"
version = "0.1.0"
authors = ["Dawei Huang <davidxuang@live.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
percent-encoding = "2.1"
url = "2.2"

[profile.release]
opt-level = "s"
lto = true
